Attribute VB_Name = "IndianStates"
'****************************************************
'   CODED BY: MANOHAR SINGH NEGI                    *
'             6th Semester , I.S.E.                 *
'             R.V. College Of Engineering           *
'             Bangalore - 560059                    *
'             manohar.negi@gmail.com                *
'                                                   *
'                                                   *
' THE DATA GIVEN HERE IS AS PER THE REFERENCE :     *
' " MANORAMA YEAR BOOK 2004 ". FOR ANY MODIFICATION *
' PLEASE HELP ME.U HAVE MY ID GIVEN ABOVE.          *
'                                                   *
'****************************************************


'****************************************************
'                                                   *
' THIS MODULE LOADS INDIAN STATES TO A COMBO BOX.   *
' HERE U NEED TO CALL THIS MODULE BY PASSING THE    *
' NAME OF THE COMBO BOX IN WHICH U WANT THESE       *
' ENTRIES TO COME.                                  *
'                                                   *
' EXAMPLE : CALL Load_States(cmbIndianStates)       *
'                                                   *
'****************************************************

Public Sub Load_States(c1 As ComboBox)
c1.CLEAR

c1.AddItem ("Andhra Pradesh")
c1.AddItem ("Arunachal Pradesh")
c1.AddItem ("Assam")
c1.AddItem ("Bihar")
c1.AddItem ("Chhattisgarh")
c1.AddItem ("Goa")
c1.AddItem ("Gujarat")
c1.AddItem ("Haryana")
c1.AddItem ("Himachal Pradesh")
c1.AddItem ("Jammu & Kashmir")
c1.AddItem ("Jharkhand")
c1.AddItem ("Karnataka")
c1.AddItem ("Kerala")
c1.AddItem ("Madhya Pradesh")
c1.AddItem ("Maharashtra")
c1.AddItem ("Manipur")
c1.AddItem ("Meghalaya")
c1.AddItem ("Mizoram")
c1.AddItem ("Nagaland")
c1.AddItem ("Orissa")
c1.AddItem ("Punjab")
c1.AddItem ("Rajasthan")
c1.AddItem ("Sikkim")
c1.AddItem ("Tamil Nadu")
c1.AddItem ("Tripura")
c1.AddItem ("Uttaranchal")
c1.AddItem ("Uttar Pradesh")
c1.AddItem ("West Bengal")
c1.AddItem ("Delhi")
c1.AddItem ("Andman & Nicobar Is.")
c1.AddItem ("Chandigarh")
c1.AddItem ("Dadra & Nagar Haveli")
c1.AddItem ("Daman & Diu")
c1.AddItem ("Lakshadweep")
c1.AddItem ("Pondicherry")
End Sub

Public Sub Load_Districts(c2 As ComboBox, STATE As String)
c2.CLEAR

Select Case STATE

Case "Andhra Pradesh"
c2.AddItem ("Anantapur")
c2.AddItem ("Chittoor")
c2.AddItem ("Cuddapah")
c2.AddItem ("Kumool")
c2.AddItem ("E. Godavari")
c2.AddItem ("Guntur")
c2.AddItem ("Krishna")
c2.AddItem ("Nellore")
c2.AddItem ("Prakasam")
c2.AddItem ("Srikakulam")
c2.AddItem ("Visakhapatnam")
c2.AddItem ("Vizianagaram")
c2.AddItem ("W. Godavari")
c2.AddItem ("Adilabad")
c2.AddItem ("Hyderabad")
c2.AddItem ("Karimnagar")
c2.AddItem ("Khamman")
c2.AddItem ("Mahaboob Nagar")
c2.AddItem ("Medak")
c2.AddItem ("Nalgonda")

Case "Arunachal Pradesh"
c2.AddItem ("Changlang")
c2.AddItem ("Dibang Velly")
c2.AddItem ("East Kameng")
c2.AddItem ("East Siang")
c2.AddItem ("Lohit")
c2.AddItem ("Lower Subansiri")
c2.AddItem ("Paum Pare")
c2.AddItem ("Tawang")
c2.AddItem ("Tirap")
c2.AddItem ("Upper Siang")
c2.AddItem ("Upper Subansiri")
c2.AddItem ("West Kameng")
c2.AddItem ("West Siang")

Case "Assam"
c2.AddItem ("Barpeta")
c2.AddItem ("Bongaigaon")
c2.AddItem ("Cachar")
c2.AddItem ("Darrang")
c2.AddItem ("Dhemaji")
c2.AddItem ("Dhubri")
c2.AddItem ("Dibrugarh")
c2.AddItem ("Goalpara")
c2.AddItem ("Golaghat")
c2.AddItem ("Hailakandi")
c2.AddItem ("North Cochar Hills")
c2.AddItem ("Jorhat")
c2.AddItem ("Kamrup")
c2.AddItem ("Karbi Anglog")
c2.AddItem ("Karimganj")
c2.AddItem ("Kokrajhar")
c2.AddItem ("Lakhimpur")
c2.AddItem ("Morigaon")
c2.AddItem ("Nagaon")
c2.AddItem ("Nalbari")
c2.AddItem ("Sibsagar")
c2.AddItem ("Sonitpur")
c2.AddItem ("Tinsukia")

Case "Bihar"
c2.AddItem ("Araria")
c2.AddItem ("Aurangabad")
c2.AddItem ("Banka")
c2.AddItem ("Begusarai")
c2.AddItem ("Bhagalpur")
c2.AddItem ("Bhojpur")
c2.AddItem ("Buxar")
c2.AddItem ("Darbhanga")
c2.AddItem ("Gaya")
c2.AddItem ("Gopalganj")
c2.AddItem ("Jahanabad")
c2.AddItem ("Jamui")
c2.AddItem ("Kaimur")
c2.AddItem ("Katihar")
c2.AddItem ("Khagaria")
c2.AddItem ("Kishanganj")
c2.AddItem ("Lakhisarai")
c2.AddItem ("Munger")
c2.AddItem ("Sheikhpura")
c2.AddItem ("Madhepura")
c2.AddItem ("Madhubani")
c2.AddItem ("Muzaffarpur")
c2.AddItem ("Nalanda")
c2.AddItem ("Nawada ")
c2.AddItem ("Paschimi Champaran")
c2.AddItem ("Patna")
c2.AddItem ("Purbi Champaran")

Case "Chhattisgarh"
c2.AddItem ("Bastar")
c2.AddItem ("Bilaspur")
c2.AddItem ("Dantewada")
c2.AddItem ("Dhamtari")
c2.AddItem ("Durg")
c2.AddItem ("Jamjgir Champa")
c2.AddItem ("Jashpur")
c2.AddItem ("Kanker")
c2.AddItem ("Kawardha")
c2.AddItem ("Korba")
c2.AddItem ("Koriya")
c2.AddItem ("Mahasamund")
c2.AddItem ("Raigarh")
c2.AddItem ("Raipur")
c2.AddItem ("Rajnandgaon")
c2.AddItem ("Sarguja")

Case "Goa"
c2.AddItem ("North Goa")
c2.AddItem ("South Goa")

Case "Gujarat"
c2.AddItem ("Ahmedabad")
c2.AddItem ("Amreli")
c2.AddItem ("Anand")
c2.AddItem ("BanasKantha")
c2.AddItem ("Bharuch")
c2.AddItem ("Bhavnagar")
c2.AddItem ("Dahod")
c2.AddItem ("Dangs")
c2.AddItem ("Gandhinagar")
c2.AddItem ("Jamnagar")
c2.AddItem ("Junagarh")
c2.AddItem ("Kheda")
c2.AddItem ("Kuchchh")
c2.AddItem ("Mahesana")
c2.AddItem ("Narmada")
c2.AddItem ("Navsari")
c2.AddItem ("Panchmahals")
c2.AddItem ("Patan")
c2.AddItem ("Porbandar")
c2.AddItem ("Rajkot")
c2.AddItem ("Sabarkantha")
c2.AddItem ("Surat")
c2.AddItem ("surendranagar")
c2.AddItem ("Vadodara")
c2.AddItem ("Valsad")

Case "Haryana"
c2.AddItem ("Ambala")
c2.AddItem ("Bhiwani")
c2.AddItem ("Faridabad")
c2.AddItem ("Fatehabad")
c2.AddItem ("Gurgaon")
c2.AddItem ("Hissar")
c2.AddItem ("Jhajjar")
c2.AddItem ("Jind")
c2.AddItem ("Kaithal")
c2.AddItem ("Karnal")
c2.AddItem ("Kurukshetra")
c2.AddItem ("Mahendragarh")
c2.AddItem ("Panchkula")
c2.AddItem ("Panipat")
c2.AddItem ("Rewari")
c2.AddItem ("Rohtak")
c2.AddItem ("Sirsa")
c2.AddItem ("Sonipat")
c2.AddItem ("Yamunanagar")

Case "Himachal Pradesh"
c2.AddItem ("Bilaspur")
c2.AddItem ("Chamba")
c2.AddItem ("Hamirpur")
c2.AddItem ("Kangra")
c2.AddItem ("Kinnaur")
c2.AddItem ("Kullu")
c2.AddItem ("Lahaul & Spiti")
c2.AddItem ("Mandi")
c2.AddItem ("Shimla")
c2.AddItem ("Sirmaur")
c2.AddItem ("Solan")
c2.AddItem ("Una")

Case "Jammu & Kashmir"
c2.AddItem ("Anantnag")
c2.AddItem ("Badgam")
c2.AddItem ("Baramula")
c2.AddItem ("Doda")
c2.AddItem ("Jammu")
c2.AddItem ("Kargil")
c2.AddItem ("Kathua")
c2.AddItem ("Kupwara")
c2.AddItem ("Ladakh")
c2.AddItem ("Pulwama")
c2.AddItem ("Poonch")
c2.AddItem ("Rajauri")
c2.AddItem ("Srinagar")
c2.AddItem ("Udhampur")

Case "Jharkhand"
c2.AddItem ("Bokaro")
c2.AddItem ("Chatra")
c2.AddItem ("Deoghar")
c2.AddItem ("Dhanbad")
c2.AddItem ("Dumka")
c2.AddItem ("Garhwa")
c2.AddItem ("Giridih")
c2.AddItem ("Godda")
c2.AddItem ("Gumla")
c2.AddItem ("Hazaribagh")
c2.AddItem ("Jamtara")
c2.AddItem ("Kodarma")
c2.AddItem ("Latehar")
c2.AddItem ("Lohardaga")
c2.AddItem ("Pakaur")
c2.AddItem ("Palamu")
c2.AddItem ("Paschimi Singhbhum")
c2.AddItem ("Purbi Singhbhum")
c2.AddItem ("Ranchi")

Case "Karnataka"
c2.AddItem ("Baglkot")
c2.AddItem ("Bangalore")
c2.AddItem ("Bangalore Rural")
c2.AddItem ("Belgaum")
c2.AddItem ("Bellary")
c2.AddItem ("Bidar")
c2.AddItem ("Bijapur")
c2.AddItem ("Chamarajanagar")
c2.AddItem ("Chickmagalur")
c2.AddItem ("Chitradurga")
c2.AddItem ("Dakshina Kannada")
c2.AddItem ("Davangere")
c2.AddItem ("Dharwad")
c2.AddItem ("Gadag")
c2.AddItem ("Gulbarga")
c2.AddItem ("Hassan")
c2.AddItem ("Haveri")
c2.AddItem ("Kodagu")
c2.AddItem ("Kolar")
c2.AddItem ("Koppal")
c2.AddItem ("Mandya")
c2.AddItem ("Mysore")
c2.AddItem ("Raichur")
c2.AddItem ("Shimoga")
c2.AddItem ("Tumkur")
c2.AddItem ("Udupi")
c2.AddItem ("Uttara Kannada")

Case "Kerala"
c2.AddItem ("Alappuzha")
c2.AddItem ("Ernakulam")
c2.AddItem ("Idukki")
c2.AddItem ("Kannur")
c2.AddItem ("Kasargod")
c2.AddItem ("Kollam")
c2.AddItem ("Kottayam")
c2.AddItem ("Kozhikode")
c2.AddItem ("Malappuram")
c2.AddItem ("Palakkad")
c2.AddItem ("Pathanamthitta")
c2.AddItem ("Thiruvananthapuram")
c2.AddItem ("Thrissur")
c2.AddItem ("Wyanad")

Case "Madhya Pradesh"
c2.AddItem ("Balaghat")
c2.AddItem ("Barwani")
c2.AddItem ("Betul")
c2.AddItem ("Bhind")
c2.AddItem ("Bhopal")
c2.AddItem ("chhatarpur")
c2.AddItem ("chhindwara")
c2.AddItem ("Damoh")
c2.AddItem ("Datia")
c2.AddItem ("Dewas")
c2.AddItem ("Dhaar")
c2.AddItem ("Dindori")
c2.AddItem ("East Nimar")
c2.AddItem ("Guna")
c2.AddItem ("Gwalior")
c2.AddItem ("Indore")
c2.AddItem ("Harda")
c2.AddItem ("Hoshangabad")
c2.AddItem ("Jabalpur")
c2.AddItem ("Jhabua")
c2.AddItem ("Katni")
c2.AddItem ("Mandla")
c2.AddItem ("Mandsaur")
c2.AddItem ("Morena")
c2.AddItem ("Narsinghpur")
c2.AddItem ("Neemuch")
c2.AddItem ("Panna")
c2.AddItem ("Raisen")
c2.AddItem ("Rajgarh")
c2.AddItem ("Ratlam")
c2.AddItem ("Rewa")
c2.AddItem ("Sagar")
c2.AddItem ("Satna")
c2.AddItem ("Sehore")
c2.AddItem ("Seoni")
c2.AddItem ("Shahdol")
c2.AddItem ("Shajapur")
c2.AddItem ("Sheopur")
c2.AddItem ("Shivpuri")
c2.AddItem ("Sidhi")
c2.AddItem ("Tikamgarh")
c2.AddItem ("Ujjain")
c2.AddItem ("Umaria")
c2.AddItem ("Vidisha")
c2.AddItem ("West Nimar")

Case "Maharashtra"
c2.AddItem ("Ahmednagar")
c2.AddItem ("Akola")
c2.AddItem ("Amaravati")
c2.AddItem ("Aurangabad")
c2.AddItem ("Beed")
c2.AddItem ("Bhandara")
c2.AddItem ("Buldana")
c2.AddItem ("Chandrapur")
c2.AddItem ("Dhule")
c2.AddItem ("Gadchiroli")
c2.AddItem ("Gondiya")
c2.AddItem ("Greater Mumbai")
c2.AddItem ("Hingoli")
c2.AddItem ("Jalgaon")
c2.AddItem ("Jalna")
c2.AddItem ("Kolhapur")
c2.AddItem ("Latur")
c2.AddItem ("Mumbai Suburban")
c2.AddItem ("Nagpur")
c2.AddItem ("Nanded")
c2.AddItem ("Nandurbar")
c2.AddItem ("Nashik")
c2.AddItem ("Osmanabad")
c2.AddItem ("Parbhani")
c2.AddItem ("Pune")
c2.AddItem ("Raigarh")
c2.AddItem ("Ratnagiri")
c2.AddItem ("Sangli")
c2.AddItem ("Satara")
c2.AddItem ("Sindhudurg")
c2.AddItem ("Solapur")
c2.AddItem ("Thane")
c2.AddItem ("Wardha")
c2.AddItem ("Washim")
c2.AddItem ("Yavatmal")

Case "Manipur"
c2.AddItem ("Bishnupur")
c2.AddItem ("Chandel")
c2.AddItem ("Churachandpur")
c2.AddItem ("Imphal East")
c2.AddItem ("Imphal West")
c2.AddItem ("Senapati")
c2.AddItem ("Tamehglong")
c2.AddItem ("Thoubal")
c2.AddItem ("Ukhrul")

Case "Meghalaya"
c2.AddItem ("East Garo Hills")
c2.AddItem ("East Khasi Hills")
c2.AddItem ("Jaintia Hills")
c2.AddItem ("Ri-Bhoi")
c2.AddItem ("South Garo Hills")
c2.AddItem ("West Garo Hills")
c2.AddItem ("West Khasi Hills")

Case "Mizoram"
c2.AddItem ("Aizawl")
c2.AddItem ("Champhai")
c2.AddItem ("Kolasib")
c2.AddItem ("Lawngtlai")
c2.AddItem ("Lunglei")
c2.AddItem ("Mamit")
c2.AddItem ("Chhimtuipui")
c2.AddItem ("Serchhip")

Case "Nagaland"
c2.AddItem ("Dimapur")
c2.AddItem ("Kohima")
c2.AddItem ("Phek")
c2.AddItem ("Mokokchung")
c2.AddItem ("Mon")
c2.AddItem ("Tuensang")
c2.AddItem ("Wokha")
c2.AddItem ("Zunheboto")

Case "Orissa"
c2.AddItem ("Angul")
c2.AddItem ("Balangir")
c2.AddItem ("Baleswar")
c2.AddItem ("Baragarh")
c2.AddItem ("Bhadrak")
c2.AddItem ("Boudh")
c2.AddItem ("Cuttack")
c2.AddItem ("Deogarh")
c2.AddItem ("Dhenkanal")
c2.AddItem ("Gajapati")
c2.AddItem ("Ganjam")
c2.AddItem ("Jagatsinghpur")
c2.AddItem ("Jajur")
c2.AddItem ("Jharsuguda")
c2.AddItem ("Kalahandi")
c2.AddItem ("Kandhamal")
c2.AddItem ("Kendrapada")
c2.AddItem ("Keonjhar")
c2.AddItem ("Khurda")
c2.AddItem ("Koraput")
c2.AddItem ("Malkanagiri")
c2.AddItem ("Mayurbhanj")
c2.AddItem ("Nabarangpur")
c2.AddItem ("Nayagarh")
c2.AddItem ("Nuapada")
c2.AddItem ("Puri")
c2.AddItem ("Rayagada")
c2.AddItem ("Sambalpur")
c2.AddItem ("Sonpur")
c2.AddItem ("sundargarh")

Case "Punjab"
c2.AddItem ("Amritsar")
c2.AddItem ("Bhathinda")
c2.AddItem ("Faridkot")
c2.AddItem ("Fatehgarh Sahib")
c2.AddItem ("Ferozepur")
c2.AddItem ("Gurdaspur")
c2.AddItem ("Hoshiarpur")
c2.AddItem ("Jalandhar")
c2.AddItem ("Kapurthala")
c2.AddItem ("Ludhiana")
c2.AddItem ("Mansa")
c2.AddItem ("Moga")
c2.AddItem ("Muktsar")
c2.AddItem ("Nawan Shehar")
c2.AddItem ("Patiala")
c2.AddItem ("Rupnagar")
c2.AddItem ("Sangrur")

Case "Rajasthan"
c2.AddItem ("Ajmer")
c2.AddItem ("Alwar")
c2.AddItem ("Banswara")
c2.AddItem ("Baran")
c2.AddItem ("Barmer")
c2.AddItem ("Bharatpur")
c2.AddItem ("Bhilwara")
c2.AddItem ("Bikaner")
c2.AddItem ("Bundi")
c2.AddItem ("Chittorgarh")
c2.AddItem ("Churu")
c2.AddItem ("Dausa")
c2.AddItem ("Dholpur")
c2.AddItem ("Dungarpur")
c2.AddItem ("Ganganagar")
c2.AddItem ("Hanumangarh")
c2.AddItem ("Jaipur")
c2.AddItem ("Jaisalmer")
c2.AddItem ("Jalore")
c2.AddItem ("Jhalawar")
c2.AddItem ("Jhunjhunu")
c2.AddItem ("Jodhpur")
c2.AddItem ("Karoli")
c2.AddItem ("Kota")
c2.AddItem ("Nagaur")
c2.AddItem ("Pali")
c2.AddItem ("Rajsamand")
c2.AddItem ("S. Madhopur")
c2.AddItem ("Sikar")
c2.AddItem ("Sirohi")
c2.AddItem ("Tonk")
c2.AddItem ("Udaipur")

Case "Sikkim"
c2.AddItem ("East Sikkim")
c2.AddItem ("North Sikkim")
c2.AddItem ("South Sikkim")
c2.AddItem ("West Sikkim")

Case "Tamil Nadu"
c2.AddItem ("Ariyalur")
c2.AddItem ("Chennai")
c2.AddItem ("Coimbatore")
c2.AddItem ("Cuddalore")
c2.AddItem ("Dharmapuri")
c2.AddItem ("Dindigul")
c2.AddItem ("Erode")
c2.AddItem ("Kancheepuram")
c2.AddItem ("Kanyakumari")
c2.AddItem ("Karur")
c2.AddItem ("Madurai")
c2.AddItem ("Nagapattinam")
c2.AddItem ("Namakkal")
c2.AddItem ("Nilgiris")
c2.AddItem ("Perambaloor")
c2.AddItem ("Pudukkottai")
c2.AddItem ("Ramanathapuram")
c2.AddItem ("Salem")
c2.AddItem ("Sivagangai")
c2.AddItem ("Thanjavur")
c2.AddItem ("Theni")
c2.AddItem ("Thiruvannamalai")
c2.AddItem ("Thiruvarur")
c2.AddItem ("Tirunelveli")
c2.AddItem ("Tiruvallur")
c2.AddItem ("Trichirappalli")
c2.AddItem ("Tuticoin")
c2.AddItem ("Vellore")
c2.AddItem ("Viluppuram")
c2.AddItem ("Virudhunagar")

Case "Tripura"
c2.AddItem ("Dhalai")
c2.AddItem ("North Tripura")
c2.AddItem ("South Tripura")
c2.AddItem ("West Tripura")

Case "Uttaranchal"
c2.AddItem ("Almora")
c2.AddItem ("Bageshwar")
c2.AddItem ("Chamoli")
c2.AddItem ("Dehradun")
c2.AddItem ("Haridwar")
c2.AddItem ("Pauri Garhwal")
c2.AddItem ("Nainital")
c2.AddItem ("Pithoragarh")
c2.AddItem ("Rudraprayag")
c2.AddItem ("Tehri Garhwal")
c2.AddItem ("Udhamsingh Nagar")
c2.AddItem ("Uttarkashi")

Case "Uttar Pradesh"
c2.AddItem ("Agra")
c2.AddItem ("Aligarh")
c2.AddItem ("Allahabad")
c2.AddItem ("Ambedkar Nagar")
c2.AddItem ("Auraiya")
c2.AddItem ("Azamgarh")
c2.AddItem ("Baghpat")
c2.AddItem ("Bahraich")
c2.AddItem ("Ballia")
c2.AddItem ("Balrampur")
c2.AddItem ("Banda")
c2.AddItem ("Bara Banki")
c2.AddItem ("Bareilly")
c2.AddItem ("Basti")
c2.AddItem ("Bijnor")
c2.AddItem ("Budaun")
c2.AddItem ("Bulandshahr")
c2.AddItem ("Chandauli")
c2.AddItem ("Chitrakut")
c2.AddItem ("Deoria")
c2.AddItem ("Etah")
c2.AddItem ("Etawah")
c2.AddItem ("Faizabad")
c2.AddItem ("Farrukhabad")
c2.AddItem ("Fatehpur")
c2.AddItem ("Firozabad")
c2.AddItem ("Gautam Budh Nagar")
c2.AddItem ("Ghaziabad")
c2.AddItem ("Ghazipur")
c2.AddItem ("Gonda")
c2.AddItem ("Gorakhpur")
c2.AddItem ("Hamirpur")
c2.AddItem ("Hardoi")
c2.AddItem ("Hathras")
c2.AddItem ("Jalaun")
c2.AddItem ("Jaunpur")
c2.AddItem ("Jhansi")
c2.AddItem ("Jyotiba Phulenagar")
c2.AddItem ("Kanauj")
c2.AddItem ("Kanput Dehat")
c2.AddItem ("Kanpur Nagar")
c2.AddItem ("Kaushambi")
c2.AddItem ("Kaushinagar")
c2.AddItem ("Kheri")
c2.AddItem ("Lalitpur")
c2.AddItem ("Lucknow")
c2.AddItem ("Maharajganj")
c2.AddItem ("Mahoba")
c2.AddItem ("Mainpuri")
c2.AddItem ("Mathura")
c2.AddItem ("Mau")
c2.AddItem ("Meerut")
c2.AddItem ("Mirzapur")
c2.AddItem ("Moradabad")
c2.AddItem ("Muzaffarnagar")
c2.AddItem ("Pilibhit")
c2.AddItem ("Pratapgarh")
c2.AddItem ("Rae Bareilly")
c2.AddItem ("Rampur")
c2.AddItem ("Saharanpur")
c2.AddItem ("Sant Kabir Nagar")
c2.AddItem ("Sant Ravidas Nagar")
c2.AddItem ("Shahjahanpur")
c2.AddItem ("Shravasti")
c2.AddItem ("Sidharth Nagar")
c2.AddItem ("Sitapur")
c2.AddItem ("Sonebhadra")
c2.AddItem ("Sultanpur")
c2.AddItem ("Unnao")
c2.AddItem ("Varanasi")

Case "West Bengal"
c2.AddItem ("Bankura")
c2.AddItem ("Birbhum")
c2.AddItem ("Bardhaman")
c2.AddItem ("Kolkata")
c2.AddItem ("Coach Behar")
c2.AddItem ("Darjeeling")
c2.AddItem ("Hooghly")
c2.AddItem ("Howrah")
c2.AddItem ("Jalpaigudi")
c2.AddItem ("Malda")
c2.AddItem ("Midnapore")
c2.AddItem ("Murshidabad")
c2.AddItem ("Nadia")
c2.AddItem ("Purulia")
c2.AddItem ("North 24 Parganas")
c2.AddItem ("South 24 Parganas")
c2.AddItem ("Uttar Dinajpur")
c2.AddItem ("Dakshin Dinajpur")

Case "Delhi"
c2.AddItem ("Delhi")

Case "Andman & Nicobar Is."
c2.AddItem ("Andman")
c2.AddItem ("Nicobar")

Case "Chandigarh"
c2.AddItem ("Chandigarh")

Case "Dadra & Nagar Haveli"
c2.AddItem ("Dadra & Nagar Haveli")

Case "Daman & Diu"
c2.AddItem ("Daman")
c2.AddItem ("Diu")

Case "Lakshadweep"
c2.AddItem ("Lakshadweep")

Case "Pondicherry"
c2.AddItem ("Pondicherry")

Case Else
c2.CLEAR

End Select
End Sub

